### ISSUE TITLE
Unable to install package on Linux.

### ISSUE THREAD

**Issue by AkhileshGahlot** [danielpaulus/go-ios#227]
**Describe the bug**
I am trying to automate IOS deviced using raspberry pi using appium. So I was trying to use this package. But when I run the install command I am facing below error. Can you please tell me which file we need inside IOS folder that the cp command trying to copy or how can I resolve this issue.

**Error: Command failed: cp ./dist/go-ios-linux-arm_linux_arm/ios ./bin/ios
cp: cannot stat './dist/go-ios-linux-arm_linux_arm/ios': No such file or directory**

Complete Error Log:

    go-ios@1.0.101 postinstall /home/user/node_modules/go-ios
    > node postinstall.js install

    Copying the relevant binary for your platform linux
    Error: Command failed: cp ./dist/go-ios-linux-arm_linux_arm/ios ./bin/ios
    cp: cannot stat './dist/go-ios-linux-arm_linux_arm/ios': No such file or directory

    at ChildProcess.exithandler (child_process.js:319:12)
    at ChildProcess.emit (events.js:376:20)
    at maybeClose (internal/child_process.js:1055:16)
    at Socket.<anonymous> (internal/child_process.js:441:11)
    at Socket.emit (events.js:376:20)
    at Pipe.<anonymous> (net.js:673:12) {
    killed: false,
    code: 1,
    signal: null,
    cmd: 'cp ./dist/go-ios-linux-arm_linux_arm/ios ./bin/ios'
    }

**Comment by danielpaulus** [comment]
Which node/npm version are you using? There seems to be a bug there.

**Comment by danielpaulus** [comment]
oh I see why, I have not compiled linux arm, only linux amd64. Let me add that.

**Comment by scottxu007** [comment]
Hey Daniel, i am also trying to using Go-iOS on Raspberry Pi. I also got the same error, have you ever fix this bug? thanks

**Comment by danielpaulus** [comment]
Oh sorry, forgot this. I am currently working on prepare, activate and erase. As soon as I got this done I will add official support for raspberry pi.

**Comment by scottxu007** [comment]
Hello Daniel, i have seen that you have released some versions for different bugs. May i ask, whether the version for Raspberry Pi is still in progress? Thanks a lot.

**Comment by scottxu007** [comment]
This issue could be closed. Pull repository in Rasp. Pi and use 'go build' to install go-ios on Rasp.Pi.

**Comment by MarioCodarin** [comment]
@scottxu007 did you successfully run Appium and the others tools on Raspberry?

> This issue could be closed. Pull repository in Rasp. Pi and use 'go build' to install go-ios on Rasp.Pi.

**Comment by danielpaulus** [comment]
Closing per the thread: linux arm64 binaries have shipped in the npm package for a while now (the release workflow builds and packages linux arm64 explicitly), and building from source with `go build` covers other setups, as found above. 32-bit arm builds are not planned. A separate pnpm postinstall crash is being fixed in #813.

_(part of an automated backlog sweep — comment or reopen if this got it wrong)_
