### ISSUE TITLE
ios apps crashes on older devices, works properly on newer devices.

### ISSUE THREAD

**Issue by compoundradius** [danielpaulus/go-ios#245]
**Describe the bug**
ios apps crashes on older devices, works properly on newer devices

```
ios version
{"version":"v1.0.106"}

```

**To Reproduce**

```
ios apps --udid=<redacted>
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x50 pc=0x6b0808]

goroutine 1 [running]:
github.com/danielpaulus/go-ios/ios/installationproxy.(*Connection).browseApps(0xc000510408, {0x8be8a0, 0xc0003d06f0})
	/home/runner/work/go-ios/go-ios/ios/installationproxy/installationproxy.go:43 +0x48
github.com/danielpaulus/go-ios/ios/installationproxy.(*Connection).BrowseUserApps(0x2)
	/home/runner/work/go-ios/go-ios/ios/installationproxy/installationproxy.go:31 +0x21b
main.printInstalledApps({0x2, {0xc000142308, 0x8}, {0x1c9c3800, {0xc000142420, 0x3}, 0x2, 0x30054, 0x12a8, {0xc0000262a0, ...}}}, ...)
	/home/runner/work/go-ios/go-ios/main.go:1186 +0xa8
main.Main()
	/home/runner/work/go-ios/go-ios/main.go:429 +0x298a
main.main()
	/home/runner/work/go-ios/go-ios/main.go:52 +0x17

```
**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
```
ios info --udid=<redacted> | python -m json.tool
{
    "BasebandCertId": redacted,
    "BasebandKeyHashInformation": {
        "AKeyStatus": 2,
        "SKeyHash": "redacted",
        "SKeyStatus": 0
    },
    "BasebandSerialNumber": "redacted",
    "BasebandVersion": "10.80.02",
    "BoardId": 0,
    "BuildVersion": "16H62",
    "ChipID": 35168,
    "DeviceClass": "iPhone",
    "DeviceColor": "#3b3b3c",
    "DeviceName": "iPhone",
    "DieID": redacted,
    "HardwareModel": "N51AP",
    "HasSiDP": true,
    "PartitionType": "GUID_partition_scheme",
    "ProductName": "iPhone OS",
    "ProductType": "iPhone6,1",
    "ProductVersion": "12.5.5",
    "ProductionSOC": true,
    "ProtocolVersion": "2",
    "TelephonyCapability": true,
    "UniqueChipID": recacted,
    "UniqueDeviceID": "redacted",
    "WiFiAddress": "redacted"
}

```

**Additional context**

Note, this command works properly on newer devices.

**Comment by compoundradius** [comment]
ideviceinstaller throws the following error against the same device and exits (does not crash).
```ideviceinstaller -u <redacted> -l -o list_system
Could not connect to lockdownd. Exiting.
```

**Comment by danielpaulus** [comment]
Closing during issue triage: this report is tied to an old go-ios/iOS version and we do not have a current reproduction. Please retest with the latest go-ios release and open a new issue, or ask us to reopen this one, with fresh logs if it still reproduces.
