### ISSUE TITLE
An error happened: Needs scheme://address is displayed when using dproxy

### ISSUE THREAD

**Issue by iTestinglab** [danielpaulus/go-ios#249]
When I tried to use `sudo./go-ios dproxy` to capture packets between xcode and iPhone, but every time I opened xcode, an error happened. ERRO[0021] Recovered a panic: Needs scheme://address

```
{"level":"info","msg":"no udid specified using first device in list","time":"2023-04-06T19:52:21+08:00","udid":"00008030-000E4CA40289802E"}
INFO[0000] Successfully retrieved pairrecord: 2CD95551-8516-404E-849B-8FFEFCB9A85E for device 00008030-000E4CA40289802E
INFO[0000] Moving socket /var/run/usbmuxd to /var/run/usbmuxd.e9cca27b-13c1-4c43-b8a1-3fe6cf5daef7.real_socket
INFO[0021] Creating binary dump of all communication between MAC OS and debugproxy at: dump-2023.04.06-11.52.21.971/connection-#1-2023.04.06-11.52.43.322/bindump-hostservice-to-proxy.txt
ERRO[0021] Recovered a panic: Needs scheme://address
INFO[0021] Moving back original socket
INFO[0021] checking if '/var/run/usbmuxd.e9cca27b-13c1-4c43-b8a1-3fe6cf5daef7.real_socket' exists
INFO[0021] found '/var/run/usbmuxd.e9cca27b-13c1-4c43-b8a1-3fe6cf5daef7.real_socket', deleting '/var/run/usbmuxd'
INFO[0021] Deleting fake socket /var/run/usbmuxd
INFO[0021] Moving back socket /var/run/usbmuxd.e9cca27b-13c1-4c43-b8a1-3fe6cf5daef7.real_socket to /var/run/usbmuxd
goroutine 35 [running]:
runtime/debug.Stack()
	/usr/local/Cellar/go/1.18.3/libexec/src/runtime/debug/stack.go:24 +0x65
runtime/debug.PrintStack()
	/usr/local/Cellar/go/1.18.3/libexec/src/runtime/debug/stack.go:16 +0x19
main.startDebugProxy.func1.1()
	/Users/charlichen/develop/open_sources/remote-devices/go-ios/main.go:1088 +0x7a
panic({0x14be900, 0x16515b0})
	/usr/local/Cellar/go/1.18.3/libexec/src/runtime/panic.go:838 +0x207
github.com/danielpaulus/go-ios/ios.GetSocketTypeAndAddress({0xc00053e000?, 0x2787888?})
	/Users/charlichen/develop/open_sources/remote-devices/go-ios/ios/usbmuxconnection.go:17 +0x68
github.com/danielpaulus/go-ios/ios.(*DeviceConnection).connectToSocketAddress(0xc0000a71a0, {0xc00053e000?, 0x0?})
	/Users/charlichen/develop/open_sources/remote-devices/go-ios/ios/deviceconnection.go:47 +0x33
github.com/danielpaulus/go-ios/ios.NewDeviceConnection(...)
	/Users/charlichen/develop/open_sources/remote-devices/go-ios/ios/deviceconnection.go:37
github.com/danielpaulus/go-ios/ios/debugproxy.startProxyConnection({_, _}, {_, _}, {{0xc0000fe0f0, 0x24}, {0xc0000fe150, 0x24}, {0xc0000b8800, 0x3c4, ...}, ...}, ...)
	/Users/charlichen/develop/open_sources/remote-devices/go-ios/ios/debugproxy/debugproxy.go:147 +0x98
github.com/danielpaulus/go-ios/ios/debugproxy.(*DebugProxy).Launch(0xc0004c4a40, {0x805, {0xc00046a980, 0x8}, {0x1c9c3800, {0xc00046aa50, 0x3}, 0x805, 0x14300000, 0x12a8, ...}}, ...)
	/Users/charlichen/develop/open_sources/remote-devices/go-ios/ios/debugproxy/debugproxy.go:141 +0x69f
main.startDebugProxy.func1()
	/Users/charlichen/develop/open_sources/remote-devices/go-ios/main.go:1094 +0xa5
created by main.startDebugProxy
	/Users/charlichen/develop/open_sources/remote-devices/go-ios/main.go:1083 +0xd2
```

**Comment by mike1023** [comment]
same error...

**Comment by danielpaulus** [comment]
I fixed this myself while decoding activation and supervision, just realized this bug. If you can use this branch https://github.com/danielpaulus/go-ios/pull/248
if not, I am about to finish these features and merge it to main in a couple of days.

**Comment by iTestinglab** [comment]
> I fixed this myself while decoding activation and supervision, just realized this bug. If you can use this branch #248 if not, I am about to finish these features and merge it to main in a couple of days.

Thanks for your reply. It works.

**Comment by danielpaulus** [comment]
The fix is merged along with a couple of new features.
