### ISSUE TITLE
Error in executing ios ax

### ISSUE THREAD

**Issue by timwang-ai** [danielpaulus/go-ios#273]
goroutine 7 [running]:
github.com/danielpaulus/go-ios/ios/accessibility.convertToStringList({0x0, 0x10, 0x8})
        /Users/runner/work/go-ios/go-ios/ios/accessibility/utils.go:4 +0x108
github.com/danielpaulus/go-ios/ios/accessibility.ControlInterface.deviceAllAuditCaseIDs({0xc0000ee000})
        /Users/runner/work/go-ios/go-ios/ios/accessibility/accessibility_control.go:198 +0xf5
github.com/danielpaulus/go-ios/ios/accessibility.ControlInterface.init({0x20})
        /Users/runner/work/go-ios/go-ios/ios/accessibility/accessibility_control.go:67 +0x338
github.com/danielpaulus/go-ios/ios/accessibility.New({0x20, {0xc00059a188, 0x8}, {0x1c9c3800, {0xc00059a256, 0x3}, 0x20, 0x1110000, 0x12a8, {0xc0001180a0, ...}}})
        /Users/runner/work/go-ios/go-ios/ios/accessibility/accessibility.go:17 +0x85
main.startAx.func1()
        /Users/runner/work/go-ios/go-ios/main.go:1019 +0xc5
created by main.startAx
        /Users/runner/work/go-ios/go-ios/main.go:1013 +0x25

**Comment by danielpaulus** [comment]
Closing during issue triage: this report is tied to an old go-ios/iOS version and we do not have a current reproduction. Please retest with the latest go-ios release and open a new issue, or ask us to reopen this one, with fresh logs if it still reproduces.
