### ISSUE TITLE
IOS ps command gives index out of range error

### ISSUE THREAD

**Issue by Selahattinn** [danielpaulus/go-ios#484]
**Describe the bug**
when I try to execute command it gives error

**Screenshots**
![image](https://github.com/user-attachments/assets/a5b8caf0-09b9-442e-944d-5c277147f1aa)

**Desktop (please complete the following information):**
 - OS: [MacOS-14.4.1,m1Pro-Yonga]

**Smartphone (please complete the following information):**
 - Device: [e.g. IPAD PRO]
 - OS: [e.g. IOS16.7.8]

**Additional context**
```
ios ps --udid a35ccaa460da7225f45b95b39fbcbda0c7ec9ebe
{"channel_id":"com.apple.instruments.server.services.deviceinfo","error":"Timed out waiting for response for message:1 channel:1","level":"info","methodselector":"runningProcesses","msg":"failed starting invoking method","time":"2024-09-26T08:54:49Z"}
panic: runtime error: index out of range [0] with length 0


goroutine 1 [running]:
github.com/danielpaulus/go-ios/ios/instruments.DeviceInfoService.ProcessList({0xc0004064e0, 0xc000406120})
	/home/runner/work/go-ios/go-ios/ios/instruments/instruments_deviceinfo.go:26 +0x137
main.processList({0x2, {0xc000306938, 0x8}, {0x1c9c3800, {0xc000306a50, 0x3}, 0x2, 0x10005, 0x12ab, {0xc000026840, ...}}}, ...)
	/home/runner/work/go-ios/go-ios/main.go:1618 +0xe8
main.Main()
	/home/runner/work/go-ios/go-ios/main.go:414 +0x41bf
main.main()
	/home/runner/work/go-ios/go-ios/main.go:57 +0x17
```

**Comment by danielpaulus** [comment]
Closing during issue triage: the exact empty-payload panic path shown here is now guarded in , and method-call errors are returned instead of indexing directly into an empty payload. If  still panics on the latest release, please open a fresh issue or ask us to reopen this one with current logs.
