### ISSUE TITLE
Does this not work on iOS 18 or iPhone 16? What is the setup, not clear anywhere?

### ISSUE THREAD

**Issue by PyroFilmsFX** [danielpaulus/go-ios#517]
`ios pair` just does:

```
panic: interface conversion: interface {} is nil, not []uint8

goroutine 1 [running]:
github.com/danielpaulus/go-ios/ios.Pair({0x2ab, {0x1400047c2d8, 0x8}, {0x0, {0x1400047c350, 0x7}, 0x2ab, 0x0, 0x0, {0x14000790c00, ...}}, ...})
	/Users/runner/work/go-ios/go-ios/ios/pair.go:176 +0x74c
main.pairDevice({0x2ab, {0x1400047c2d8, 0x8}, {0x0, {0x1400047c350, 0x7}, 0x2ab, 0x0, 0x0, {0x14000790c00, ...}}, ...}, ...)
	/Users/runner/work/go-ios/go-ios/main.go:2253 +0x54
main.Main()
	/Users/runner/work/go-ios/go-ios/main.go:750 +0x1f60
main.main()
	/Users/runner/work/go-ios/go-ios/main.go:60 +0x1c
```

`ENABLE_GO_IOS_AGENT=yes sudo ios tunnel start --udid {my udid}` shows:
{"level":"warning","msg":"go-ios agent is not running. You might need to start it with 'ios tunnel start' for ios17+. Use ENABLE_GO_IOS_AGENT=yes for experimental daemon mode.","time":"2024-11-18T14:30:01-06:00"}
{"level":"info","msg":"Tunnel server started","time":"2024-11-18T14:30:01-06:00"}
{"level":"info","msg":"start tunnel","time":"2024-11-18T14:30:02-06:00","udid":"{my udid}"}
{"level":"info","msg":"connect to lockdown tunnel endpoint on device","time":"2024-11-18T14:30:02-06:00"}

This is 100% the latest version:
`{"version":"v1.0.158"}`

ios screenshot
{"level":"info","msg":"no udid specified using first device in list","time":"2024-11-18T14:30:27-06:00","udid":"{my udid}"}
{"level":"info","msg":"no udid specified using first device in list","time":"2024-11-18T14:30:27-06:00","udid":"{my udid}"}
{"err":"ConnectToServiceTunnelIface: failed to connect to tunnel: ConnectToHttp2WithAddr: failed to dial: dial tcp [fd02:a126:{redacted}::1]:0: connect: can't assign requested address","level":"fatal","msg":"Starting screenshot service failed","time":"2024-11-18T14:30:27-06:00"}

The device correctly and fully works with my m1 Macbook with things like iPhone Mirroring.app

Where and how do I start the go-ios agent. That is explained no where. Providing the ENABLE_GO_IOS_AGENT directly for via env export does nothing.

Pair fails with an exception, yet tunnel states its connected and logs appear when attempting to screenshot.

Do I need WDA? Do I need a developer image? What does that even mean in this case?

Can you please provide me with some explanation on setup and use. The readme provides no useful information, neither does the output of the commands nor the manpage.

**Comment by PyroFilmsFX** [comment]
Bumping please

**Comment by PyroFilmsFX** [comment]
Hello

**Comment by NintyS** [comment]
bump

**Comment by danielpaulus** [comment]
iOS 18 and iPhone 16 are supported. The `ios pair` panic is fixed — pair.go now returns a proper error instead of panicking — and the root cause matches what @bsanz-intern found: the nil DevicePublicKey comes from the device being listed via a Wi-Fi usbmuxd entry; pair over USB (or disable Wi-Fi on the device while pairing) and it succeeds. On setup: `ios tunnel start` in one terminal IS the agent (`ENABLE_GO_IOS_AGENT=user|kernel` just makes other commands auto-spawn it — note `yes` is no longer a valid value); your screenshot `dial ...:0` error just means that tunnel wasn't actually up yet. The DDI (`ios image auto`) and WDA are only needed for UI testing, not basic commands. Please retest on the latest release and open a fresh issue if a specific command still fails.

_(part of an automated backlog sweep — comment or reopen if this got it wrong)_
