### ISSUE TITLE
dproxy TLS failure

### ISSUE THREAD

**Issue by nanoscopic** [danielpaulus/go-ios#66]
When I attempt to use dproxy to monitor launching WDA through Xcode I get the following failure:
```
INFO[0011] Creating binary dump of all communication between MAC OS and debugproxy at: dump-2021.10.07-22.26.17.663/connection-#115-2021.10.07-22.26.29.101/bindump-hostservice-to-proxy.txt
INFO[0011] map[Label:xcodebuild ProtocolVersion:2 Request:QueryType]  ID="#115" direction=host2device id="#115"
INFO[0011] done sending to device                        id="#115"
INFO[0011] map[Request:QueryType Type:com.apple.mobile.lockdown]  ID="#115" direction=device2host id="#115"
INFO[0011] map[Key:ProductName Label:xcodebuild ProtocolVersion:2 Request:GetValue]  ID="#115" direction=host2device id="#115"
INFO[0011] done sending to device                        id="#115"
INFO[0011] map[Key:ProductName Request:GetValue Value:iPhone OS]  ID="#115" direction=device2host id="#115"
INFO[0011] Handshake errorwrite unix /var/run/usbmuxd->: write: broken pipe
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x24 pc=0x1255277]

goroutine 148 [running]:
crypto/tls.(*Conn).handshakeContext(0x0, {0x14b43d0, 0xc00001a098})
	/usr/local/go/src/crypto/tls/conn.go:1432 +0x1d7
crypto/tls.(*Conn).HandshakeContext(...)
	/usr/local/go/src/crypto/tls/conn.go:1395
crypto/tls.(*Conn).Handshake(...)
	/usr/local/go/src/crypto/tls/conn.go:1379
crypto/tls.(*Conn).Read(0x0, {0xc00009432c, 0x4, 0x104b072})
	/usr/local/go/src/crypto/tls/conn.go:1264 +0x65
io.ReadAtLeast({0x1f8a340, 0x0}, {0xc00009432c, 0x4, 0x4}, 0x4)
	/usr/local/go/src/io/io.go:328 +0x9a
io.ReadFull(...)
	/usr/local/go/src/io/io.go:347
encoding/binary.Read({0x1f8a340, 0x0}, {0x14b9320, 0x17688b8}, {0x139e980, 0xc0004fb200})
	/usr/local/go/src/encoding/binary/binary.go:166 +0xc8
github.com/danielpaulus/go-ios/ios.PlistCodec.Decode({}, {0x1f8a340, 0x0})
	/Users/user/git/go-ios/ios/plistcodec.go:48 +0x94
github.com/danielpaulus/go-ios/ios.(*LockDownConnection).ReadMessage(0x13ba160)
	/Users/user/git/go-ios/ios/lockdown.go:60 +0x27
github.com/danielpaulus/go-ios/ios/debugproxy.proxyLockDownConnection(0xc0000c4b40, 0xc00034b620, 0xc00034b648)
	/Users/user/git/go-ios/ios/debugproxy/lockdownhandler.go:14 +0x53
github.com/danielpaulus/go-ios/ios/debugproxy.handleConnectToLockdown({{0x23b, 0x1, 0x8, 0x17}, {0xc0001d6d80, 0x22b, 0x22b}}, 0x9, 0x0, 0xc000098f00, ...)
	/Users/user/git/go-ios/ios/debugproxy/muxhandler.go:121 +0x217
github.com/danielpaulus/go-ios/ios/debugproxy.handleConnect({{0x23b, 0x1, 0x8, 0x17}, {0xc0001d6d80, 0x22b, 0x22b}}, 0x3ed, 0xc0000c4b40, 0xc000098f00, ...)
	/Users/user/git/go-ios/ios/debugproxy/muxhandler.go:100 +0x18d
github.com/danielpaulus/go-ios/ios/debugproxy.proxyUsbMuxConnection(0xc0000c4b40, 0xc000098f00, 0xc000098f18)
	/Users/user/git/go-ios/ios/debugproxy/muxhandler.go:37 +0xe65
created by github.com/danielpaulus/go-ios/ios/debugproxy.startProxyConnection
	/Users/user/git/go-ios/ios/debugproxy/debugproxy.go:156 +0x6d6
```

**Comment by danielpaulus** [comment]
this works now
